### ISSUE TITLE
is it working 

### ISSUE THREAD

**Issue by ErcanBalbay** [Hell-Fire/WidebandO2#2]
did you tested program and pcb ? any problems?

**Comment by Hell-Fire** [comment]
I had some level of operation going, but I never had anything to compare it against to ensure correct operation, I believe it ended up being "close enough" for narrowband simulation, but it has been a long time since I've used the circuit and code in a running vehicle.  I currently don't have the equipment, or a vehicle for that matter, to do any further development/testing.

**Comment by ErcanBalbay** [comment]
Thank you :) I have ordered LSU 4.9 when it arrived i will try it with Arduino Uno Board.
