### ISSUE TITLE
lsu 4.9 connection

### ISSUE THREAD

**Issue by ErcanBalbay** [Hell-Fire/WidebandO2#4]
i have a question about lsu4.9 connection.

6 wires on lsu 4.9 but 8 wires on your circuit. how is the wiring of them. for ex +2.5v ?

**Comment by Hell-Fire** [comment]
Ahh, so my original connector to the LSU4.9 was off the TechEdge unit, the complexity of that unit is what drove me to design this circuit, I honestly haven't looked at anything on this circuit for a very long time (years), my recollection being that the majority of the heavy analog lifting was performed by a quad op-amp, and the Teensy doing quite a number of tricks to pull everything together, but it's entirely likely I got something wrong with the design and it doesn't work as intended.  (From memory, I think I only got it to the point that it was about as good as a narrowband replacement (which for my car was great, since the LSU4.9 was available for cheaper than it's original narrowband sensor), but I also remember ending up replacing it with another sensor that had a controller inline in the cable at some point along the way, making this unit obsolete, so your results may vary).
